import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import NextAuthProvider from "@/provider/NextAuthProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "VolTic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextAuthProvider>
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased  mx-auto bg-white ` }
      >
        {/* header section */}
        <header>
          <Navbar></Navbar>
        </header>
        
        {/* main section */}
        <main>
          {children}
        </main>

        {/* footer section */}
        <footer>
          <Footer></Footer>
        </footer>
      </body>
    </html>
    </NextAuthProvider>
  );
}
